@startuml

component "background_manager" as "background_manager"
  where:
    background_manager.__init__ --> background_manager.animate_transition
    background_manager.get_colors --> background_manager.interpolate_color
    background_manager.update_background --> background_manager.update_frame

component "main" as "main"
  where:
    main.__init__ --> main.create_datetime_display
    main.create_footer --> main.create_forecast_section
    main.create_location_section --> main.create_weather_display
    main.get_weather --> main.initialize_excel_log
    main.log_to_excel --> main.update_datetime
    main.update_forecast_display --> main.update_forecast_icon
    main.update_temperature_display --> main.update_weather_display
    main.update_weather_display --> main.update_weather_icon

component "main" as "main"
  where:
    main.__init__ --> background_manager

component "background_manager" as "background_manager"
  where:
    background_manager.imports --> main

component "PIL" as "PIL"
where:
    PIL --> main

component "datetime" as "datetime"
where:
    datetime --> main

component "io" as "io"
where:
    io --> main

component "os" as "os"
where:
    os --> main

component "pandas" as "pandas"
where:
    pandas --> main

component "requests" as "requests"
where:
    requests --> main

component "tkinter" as "tkinter"
where:
    tkinter --> background_manager
    tkinter --> main

@enduml